### ISSUE TITLE
A bit confused as to how the tests work

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-operators-lab#2]
(they don't know variables)

You are putting a operator into a variable, and asserting it's true-ness. I found that a bit confusing, maybe walk them through solving one, then ask them to solve the rest?

**Comment by jmburges** [comment]
Remember this is like their third JS code they are _ever_ writing

**Comment by pletcher** [comment]
I moved this later in the curriculum, so students shouldn't be taken aback by variables anymore.

**Comment by pletcher** [comment]
Actually, given that we probably want to strike the README that goes with this, I'm inclined to strike this and do a different sort of lab.
